### ISSUE TITLE
Botsing plugin - can't set class path

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/stamp-ide#30]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: block
- **Tool/Service/Component**: Botsing Wizard
- **Execution Environment**: Windows 10, Eclipse Photon
- **Reporter**: Lars Thomas Boye

#### Description
I select a folder for the "Class Path" field, but the field remains empty in the wizard. Pressing Finish, nothing happens (no console output, no errors).

**Comment by jesus-gorronogoitia** [comment]
Hi @RicardoTej please, discuss with @ltboye this issue.

**Comment by RicardoTej** [comment]
Good afternoon 

Could I get the folder of your example ? to reproduce the problem

Thank you.

**Comment by ltboye** [comment]
I'm not sure I understand the question. I am trying to run the plugin on an example in EvoCrash-Demo. So I have cloned the EvoCrash-Demo project. For class path I select a folder in this project, such as
EvoCrash-demo\Demo\src\resources\targetedSoftware\XWIKI-bins\XWIKI-7.4

**Comment by jesus-gorronogoitia** [comment]
Hi @RicardoTej 
The problem reported by @ltboye is that when he selects a classpath folder, the field remains empty. I assume the plugin creates a classpath srring in that field with all the jars located in selected folder, doesn't it? So, please, try it with the same EvoCrash-demo\Demo\src\resources\targetedSoftware\XWIKI-bins\XWIKI-7.4 to see what happens. You have this folder, since you tested the Evocrash demo.

**Comment by jesus-gorronogoitia** [comment]
Hi @ltboye this issue should have been fixed in latest Botsing plugin for Eclipse, version 1.0.0.201811271630.
Please, update your Eclipse instance and try it again. Thanks.

**Comment by ltboye** [comment]
I can confirm that selecting the classpath works in the latest version.
